name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make dir
      run: mkdir -p build
           cd build
    - name: run cmake
      run: cmake ../src/ -DCMAKE_INSTALL_PREFIX=`kf5-config --prefix` -DKDE_INSTALL_QTPLUGINDIR=`kf5-config --qt-plugins`
    - name: run make
      run: make
    - uses: actions/upload-artifact@v4
            with:
              path: ${{github.workspace}}/build
