name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: make dir
        run: |
          mkdir -p build
          cd build
      - name: run cmake
        run: cmake ../src/
      - name: run make
        run: make
      - uses: actions/upload-artifact@v4
        with:
          path: ${{github.workspace}}/build
